{"type":"PR","pr":{"number":3,"head":"dbc61b4ea1ff7cdf88d950514d03a6ff0fc74f7f"},"user":"dackalacbayo","status":"draft","branch":"cms/2019-02-08-failed-to-persist-entry-api_error-reference-already-exists","collection":"blog","title":"Failed to persist entry: API_ERROR: Reference already exists","description":"No Description!","objects":{"entry":{"path":"content/posts/2019-02-08-failed-to-persist-entry-api_error-reference-already-exists.md","sha":"25626e75044ade4863ac725e8653befeaf59b3c0"},"files":[]},"timeStamp":"2019-02-08T07:20:47.307Z"}